# Generated by Django 3.1.7 on 2021-03-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_auto_20210310_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_id',
            field=models.TextField(default=''),
        ),
    ]
