# Generated by Django 3.1.7 on 2021-03-11 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_auto_20210311_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
