# Generated by Django 3.1.7 on 2021-03-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0013_auto_20210311_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.CharField(default='', max_length=50),
        ),
    ]
